# Generated by Django 5.2 on 2025-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='action_signal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='model_type',
            field=models.CharField(default='random_forest', max_length=20),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='price_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['model_type'], name='predictor_p_model_t_d55aab_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['stock_symbol', 'model_type'], name='predictor_p_stock_s_8ac8c8_idx'),
        ),
    ]
