# Generated by Django 5.2 on 2025-05-02 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionresult_action_signal_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='predictionresult',
            name='predictor_p_stock_s_8ac8c8_idx',
        ),
        migrations.RenameField(
            model_name='predictionresult',
            old_name='price_target',
            new_name='predicted_price',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='action_signal',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='target_date',
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='predicted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='model_type',
            field=models.CharField(choices=[('random_forest', 'Random Forest'), ('lightgbm', 'LightGBM'), ('xgboost', 'XGBoost'), ('catboost', 'CatBoost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='probability_down',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='probability_up',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='signal',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Hold', 'Hold'), ('Error', 'Error')], max_length=10),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['stock_symbol'], name='predictor_p_stock_s_d9707c_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['timestamp'], name='predictor_p_timesta_26cf4a_idx'),
        ),
    ]
